{% set name = "opr" %}
{% set version = "0.3" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/opr
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.6
    run:
        - python >=3.6
about:
    home: https://github.com/openscilab/opr
    license: MIT
    license_family: MIT
    summary: Python library for machine learning input and output
    description: |
        OPR is an open-source Python package designed to simplify and streamline primer design and analysis for biologists and bioinformaticians. OPR enables users to design, validate, and optimize primers with ease, catering to a wide range of applications such as PCR, qPCR, and sequencing. With a focus on user-friendliness and efficiency, OPR aims to bridge the gap between biological research and computational tools, making primer-related workflows faster and more reliable.
        
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/opr
extra:
    recipe-maintainers:
        - sepandhaghighi
        - AHReccese
        - sadrasabouri
